import React, { useState } from 'react';
import { Landmark, CheckCircle2, AlertTriangle, Scale, ExternalLink } from 'lucide-react';
import { COMPLIANCE_SOURCES } from '../data/complianceSources';

interface CodeCard { id: string; name: string; purpose: string; currentPoints: string[]; evidence: string[]; sourceIds: string[]; }

const CODES: CodeCard[] = [
  { id: 'wages', name: 'Code on Wages, 2019', purpose: 'Wages, minimum wages, payment of wages, deductions, equality and overtime.', currentPoints: ['Minimum-wage coverage is universalised across employees.', 'The statutory wage definition can add back excess excluded components for statutory calculations.', 'Overtime under the Code is at least twice the normal rate where the Code provision applies.', 'State/appropriate-government rules still matter for establishment-specific working arrangements.'], evidence: ['Salary structures', 'Payroll register', 'Minimum-wage notification by state/category', 'Attendance and overtime data'], sourceIds: ['mole-labour-codes-effective', 'mole-code-wages-rules-2026'] },
  { id: 'social-security', name: 'Code on Social Security, 2020', purpose: 'EPF, ESI, gratuity, maternity and related social-security provisions.', currentPoints: ['Current social-security rules are now in force and must be used with establishment facts.', 'Direct fixed-term employment and contractor labour are distinct categories.', 'Gratuity treatment for direct fixed-term employees requires specific testing from the contract start date.', 'EPFO/ESIC operational evidence should be reconciled to the employee master and payroll.'], evidence: ['Employee master', 'EPFO/ESIC records', 'Gratuity calculations', 'Maternity records', 'Fixed-term contracts'], sourceIds: ['mole-social-security-rules-2026', 'mole-labour-handbook-2026'] },
  { id: 'industrial-relations', name: 'Industrial Relations Code, 2020', purpose: 'Industrial disputes, trade unions, standing orders and related employment relations.', currentPoints: ['Use the 2026 Central Rules where centrally governed.', 'Applicability depends on the establishment and worker population.', 'Retrenchment, closure and collective-bargaining actions require fact-specific review.', 'Do not import legacy thresholds or forms without checking the current rules.'], evidence: ['Worker classification', 'Standing orders where applicable', 'Industrial-relations records', 'Retrenchment/closure documentation'], sourceIds: ['mole-ir-rules-2026'] },
  { id: 'oshwc', name: 'Occupational Safety, Health and Working Conditions Code, 2020', purpose: 'Registration, working conditions, health, safety, welfare, contract labour and migrant-worker provisions.', currentPoints: ['The 2026 Central Rules provide current registration and operational forms.', 'Working-condition requirements vary by establishment and worker category.', 'Night work and women night work require current state-specific verification.', 'Contract labour and migrant-worker controls require classification and vendor evidence.'], evidence: ['Establishment registration', 'Safety/health records', 'Shift rosters', 'Contractor register', 'Applicable state notifications'], sourceIds: ['mole-osh-rules-2026'] }
];

export const LabourCodesMatrix: React.FC = () => {
  const [selected, setSelected] = useState(CODES[0]);
  return (
    <div className="bg-white text-slate-900 min-h-screen py-10 px-4 sm:px-6 lg:px-8 font-sans">
      <div className="max-w-7xl mx-auto space-y-8">
        <header className="space-y-3"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-indigo-50 border border-indigo-200 text-indigo-700 text-xs font-semibold"><Landmark className="w-3.5 h-3.5" /> Current Labour Code transition reference</div><h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">The 4 Labour Codes — HR Readiness Matrix</h1><p className="text-slate-600 text-sm max-w-4xl leading-relaxed">The four central Labour Codes are in force. This page explains the current framework and the evidence a CHRO should collect; it intentionally does not turn a code summary into a legal certification.</p></header>
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-950 flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0" /><span><strong>Do not use legacy checklists blindly.</strong> The 2026 Central Rules supersede several legacy central rules. State rules and notifications remain part of the applicability analysis.</span></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{CODES.map(code => <button key={code.id} type="button" onClick={() => setSelected(code)} className={`p-5 rounded-2xl border text-left transition ${selected.id === code.id ? 'bg-indigo-50 border-indigo-400 ring-1 ring-indigo-200' : 'bg-slate-50 border-slate-200 hover:bg-slate-100'}`}><span className="text-[10px] font-bold uppercase tracking-wider text-indigo-700">Current code</span><h2 className="mt-2 text-base font-bold">{code.name}</h2><p className="mt-2 text-xs text-slate-600">{code.purpose}</p></button>)}</div>
        <section className="bg-slate-50 p-6 sm:p-8 rounded-2xl border border-slate-200 space-y-6">
          <div><h2 className="text-2xl font-bold">{selected.name}</h2><p className="mt-2 text-sm text-slate-600">{selected.purpose}</p></div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><div><h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 flex items-center gap-2"><Scale className="w-4 h-4" /> Current framework points</h3><div className="mt-3 space-y-2">{selected.currentPoints.map(point => <div key={point} className="bg-white p-3 rounded-xl border border-slate-200 text-xs text-slate-700 leading-relaxed">{point}</div>)}</div></div><div><h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">Evidence a CHRO should collect</h3><div className="mt-3 space-y-2">{selected.evidence.map(item => <div key={item} className="bg-white p-3 rounded-xl border border-slate-200 text-xs text-slate-700 flex gap-2"><CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />{item}</div>)}</div></div></div>
          <div className="border-t border-slate-200 pt-4"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-500 mb-2">Primary sources</div><div className="flex flex-wrap gap-2">{selected.sourceIds.map(id => { const source = COMPLIANCE_SOURCES.find(s => s.id === id); return source ? <a key={id} href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-md border border-slate-200 bg-white px-2 py-1 text-[10px] font-semibold text-indigo-700"><ExternalLink className="w-3 h-3" />{source.authority}</a> : null; })}</div></div>
          <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs text-blue-950">Next step: open <strong>Compliance Control Center</strong> and assess the actual establishment/site. A code reference does not create PASS/FAIL by itself.</div>
        </section>
      </div>
    </div>
  );
};
