import React, { useState } from 'react';
import { FileText, Copy, Check, Search, ShieldCheck, AlertTriangle } from 'lucide-react';

interface EvidenceTemplate { id: string; name: string; purpose: string; sourceBasis: string; fields: string[]; }

const TEMPLATES: EvidenceTemplate[] = [
  { id: 'site-register', name: 'Establishment / Outlet Compliance Record', purpose: 'Internal evidence record linking a workplace to its legal entity, state, registration and responsible owner.', sourceBasis: 'Current establishment law + OSHWC / applicable state rules', fields: ['Site / outlet ID', 'Legal entity', 'Full address', 'State / district', 'Establishment type', 'Registration / licence reference', 'Issue / expiry dates', 'Responsible HR / compliance owner', 'Source URL and verification date'] },
  { id: 'payroll-evidence', name: 'Payroll & Wage Evidence Pack', purpose: 'Internal evidence checklist for wage, overtime, minimum-wage and statutory deduction testing.', sourceBasis: 'Code on Wages, 2019 + applicable state rules + current payroll/statutory guidance', fields: ['Wage period', 'Worker category', 'Minimum-wage source', 'Attendance source', 'OT calculation', 'Gross / wage components', 'EPF/ESI basis', 'Remittance reference', 'Reviewer and verification date'] },
  { id: 'posh-evidence', name: 'POSH Governance Evidence Pack', purpose: 'Internal checklist for workplace-level POSH governance without reproducing confidential complaint information.', sourceBasis: 'POSH Act, 2013 and applicable rules', fields: ['Workplace / entity', 'IC constitution evidence', 'Presiding Officer', 'External member evidence', 'Policy version', 'Training evidence', 'Annual report evidence', 'Complaint-process controls', 'Reviewer and verification date'] },
  { id: 'contractor-evidence', name: 'Contractor Compliance Evidence Pack', purpose: 'Internal vendor/site evidence checklist for contract workers.', sourceBasis: 'OSHWC / current contract-labour rules and applicable state requirements', fields: ['Contractor legal name', 'Site / outlet assignment', 'Worker count', 'Contract/SOW', 'Registration/licence evidence', 'Wage-payment evidence', 'Statutory remittance evidence', 'Expiry/renewal date', 'Reviewer and verification date'] },
  { id: 'night-work', name: 'Night Work Safeguards Evidence Pack', purpose: 'Internal evidence checklist for late-night and women-night-work arrangements.', sourceBasis: 'OSHWC / current state notifications and establishment rules', fields: ['Site', 'Shift window', 'Worker categories', 'Applicable state source', 'Transport arrangement', 'Security controls', 'Incident escalation', 'Review date', 'Responsible owner'] }
];

export const StatutoryFormVault: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selected, setSelected] = useState(TEMPLATES[0]);
  const [copied, setCopied] = useState(false);
  const filtered = TEMPLATES.filter(item => `${item.name} ${item.purpose} ${item.sourceBasis}`.toLowerCase().includes(searchTerm.toLowerCase()));
  const templateText = selected.fields.map((field, index) => `${index + 1}. ${field}: ______________________________`).join('\n');

  const copy = () => { navigator.clipboard.writeText(`${selected.name}\n\n${selected.purpose}\n\n${templateText}`); setCopied(true); setTimeout(() => setCopied(false), 2000); };

  return (
    <div className="bg-white text-slate-900 min-h-screen py-10 px-4 sm:px-6 lg:px-8 font-sans"><div className="max-w-7xl mx-auto space-y-8">
      <header className="space-y-3"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-indigo-50 border border-indigo-200 text-indigo-700 text-xs font-semibold"><FileText className="w-3.5 h-3.5" /> Evidence template vault</div><h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">Compliance Evidence & Filing Workspace</h1><p className="text-slate-600 text-sm max-w-4xl leading-relaxed">These are internal evidence templates, not government-prescribed forms. Official forms and filing workflows must always be obtained from the applicable government portal or current rules.</p></header>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-950 flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0" /><span><strong>Never submit a ComplyOS template as an official statutory form.</strong> Verify the operative form, portal, authority and due date before filing.</span></div>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8"><div className="lg:col-span-5 space-y-3"><div className="relative"><Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" /><input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search evidence template…" className="w-full bg-slate-50 pl-10 pr-4 py-2.5 rounded-xl border border-slate-200 text-xs" /></div>{filtered.map(item => <button type="button" key={item.id} onClick={() => setSelected(item)} className={`w-full p-4 rounded-xl border text-left ${selected.id === item.id ? 'bg-indigo-50 border-indigo-400' : 'bg-slate-50 border-slate-200'}`}><h2 className="text-sm font-bold">{item.name}</h2><p className="mt-1 text-xs text-slate-600 leading-relaxed">{item.purpose}</p></button>)}</div>
      <div className="lg:col-span-7"><div className="bg-slate-50 p-6 sm:p-8 rounded-2xl border border-slate-200 space-y-5"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wide text-indigo-700">Internal template</span><h2 className="mt-1 text-xl font-bold">{selected.name}</h2><p className="mt-2 text-xs text-slate-600">{selected.purpose}</p></div><button type="button" onClick={copy} className="px-3 py-2 bg-white rounded-lg border border-slate-300 text-xs font-semibold flex items-center gap-1.5">{copied ? <><Check className="w-3.5 h-3.5 text-emerald-600" />Copied</> : <><Copy className="w-3.5 h-3.5" />Copy</>}</button></div><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Source basis</div><p className="mt-2 text-xs text-slate-700">{selected.sourceBasis}</p></div><textarea readOnly rows={18} value={templateText} className="w-full bg-white text-slate-800 text-xs p-4 rounded-xl border border-slate-300 font-mono leading-relaxed" /><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs text-blue-950 flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0" /><span>Evidence should include its source, collection date, reviewer and verification status. A completed template is not proof of compliance until the underlying evidence is accepted.</span></div></div></div></div>
    </div></div>
  );
};
