import React, { useMemo, useState } from 'react';
import { Calculator, AlertTriangle, ExternalLink, ShieldCheck } from 'lucide-react';

const INR = (value: number) => `₹${Math.round(value).toLocaleString('en-IN')}`;

export const StatutoryCalculator: React.FC = () => {
  const [totalRemuneration, setTotalRemuneration] = useState('');
  const [basicDa, setBasicDa] = useState('');
  const [allowances, setAllowances] = useState('');
  const [otherComponents, setOtherComponents] = useState('');

  const result = useMemo(() => {
    const remuneration = Number(totalRemuneration);
    const basic = Number(basicDa);
    const allowance = Number(allowances);
    const other = Number(otherComponents);
    if (![remuneration, basic, allowance, other].every(Number.isFinite) || remuneration <= 0 || basic < 0 || allowance < 0 || other < 0) return null;
    const threshold = remuneration * 0.5;
    const excess = Math.max(0, allowance - threshold);
    return { remuneration, basic, allowance, other, threshold, excess, revisedWages: basic + excess };
  }, [totalRemuneration, basicDa, allowances, otherComponents]);

  return <div className="bg-white text-slate-900 min-h-screen py-10 px-4 sm:px-6 lg:px-8 font-sans"><div className="max-w-6xl mx-auto space-y-8">
    <header className="space-y-3"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-indigo-50 border border-indigo-200 text-indigo-700 text-xs font-semibold"><Calculator className="w-3.5 h-3.5" /> Evidence-first payroll calculator</div><h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">Code on Wages — 50% Allowance Rule Check</h1><p className="text-slate-600 text-sm max-w-4xl leading-relaxed">Use actual monthly remuneration components to model the 50% wage-definition add-back. This is a calculation aid, not a determination of EPF, ESI, gratuity, tax or state-law liability.</p></header>
    <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-950 flex gap-2"><AlertTriangle className="w-4 h-4 shrink-0" /><span><strong>Do not use CTC as a proxy.</strong> The Ministry's current FAQ illustration applies the 50% test to total remuneration; gratuity and retrenchment compensation are excluded from the allowance bucket. Verify the component classification under Section 2(y) for the actual payroll structure.</span></div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8"><section className="bg-slate-50 p-6 rounded-2xl border border-slate-200 space-y-4"><h2 className="text-sm font-bold uppercase tracking-wide">Actual payroll inputs</h2><label className="block text-xs"><span className="font-semibold text-slate-600">Total monthly remuneration used for the wage test</span><input type="number" min={0} value={totalRemuneration} onChange={e => setTotalRemuneration(e.target.value)} placeholder="₹ actual remuneration" className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="block text-xs"><span className="font-semibold text-slate-600">Basic + Dearness Allowance</span><input type="number" min={0} value={basicDa} onChange={e => setBasicDa(e.target.value)} placeholder="₹ actual Basic + DA" className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="block text-xs"><span className="font-semibold text-slate-600">Allowances / benefits subject to the 50% rule</span><input type="number" min={0} value={allowances} onChange={e => setAllowances(e.target.value)} placeholder="₹ actual allowance bucket" className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-3" /></label><label className="block text-xs"><span className="font-semibold text-slate-600">Other remuneration components excluded from the allowance bucket</span><input type="number" min={0} value={otherComponents} onChange={e => setOtherComponents(e.target.value)} placeholder="₹ e.g. gratuity / retrenchment" className="mt-1 w-full rounded-xl border border-slate-300 bg-white p-3" /></label></section>
    <section className="bg-slate-50 p-6 rounded-2xl border border-slate-200 space-y-4"><h2 className="text-sm font-bold uppercase tracking-wide">Modelled result</h2>{!result ? <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-xs text-slate-500">Enter actual payroll components to calculate. No sample salary is preloaded.</div> : <><div className="grid grid-cols-2 gap-3"><div className="bg-white p-4 rounded-xl border border-slate-200"><div className="text-[10px] text-slate-500">50% threshold</div><div className="mt-1 text-2xl font-black">{INR(result.threshold)}</div></div><div className="bg-white p-4 rounded-xl border border-slate-200"><div className="text-[10px] text-slate-500">Modelled add-back</div><div className="mt-1 text-2xl font-black text-indigo-700">{INR(result.excess)}</div></div></div><div className={`rounded-xl p-4 border ${result.excess > 0 ? 'bg-amber-50 border-amber-200 text-amber-950' : 'bg-emerald-50 border-emerald-200 text-emerald-950'}`}><strong>{result.excess > 0 ? 'Potential wage-definition add-back' : 'No add-back indicated by this model'}</strong><p className="mt-1 text-xs leading-relaxed">Modelled statutory wage base after add-back: {INR(result.revisedWages)}. Confirm the component classification under Section 2(y), then separately recalculate each affected statutory contribution/benefit.</p></div></>}</section></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 text-xs text-slate-600 flex gap-2"><ShieldCheck className="w-4 h-4 text-indigo-600 shrink-0" /><span>Primary reference: <a className="text-indigo-700 font-semibold" href="https://labour.gov.in/static/uploads/2026/01/de4758d5bfeffc456d7de97a801891b0.pdf" target="_blank" rel="noreferrer">Ministry of Labour & Employment — Code on Wages FAQ</a>. The calculator does not calculate EPF/ESI/gratuity/Professional Tax because those require separate current rules and employee/establishment facts.</span><ExternalLink className="w-3.5 h-3.5 text-indigo-600" /></div>
  </div></div>;
};
